/**
 * Fix Story Video Generator
 * 
 * After a successful BugBot run, generates a short "Fix Story" video
 * (2-4 min) that explains:
 * - What the bug was
 * - Why it happened (root cause)
 * - What changed (diff walkthrough)
 * - How tests prove the fix works
 * 
 * Reuses the existing Remotion pipeline and manifest concepts.
 */

import type { AgentRun } from "@/lib/agentRuns";

export interface FixStoryScene {
  id: string;
  type: "intro" | "bug_context" | "root_cause" | "diff_walkthrough" | "test_results" | "summary";
  title: string;
  narration: string;
  durationSeconds: number;
  visualConfig: FixStoryVisualConfig;
  data: Record<string, unknown>;
}

export interface FixStoryVisualConfig {
  layout: "centered" | "split" | "code" | "terminal" | "graph";
  background: "dark" | "gradient" | "mesh";
  accentColor: string;
  animation: "fade" | "slide" | "zoom" | "typewriter";
  codeHighlight?: {
    language: string;
    theme: "dark";
    additions: number[];
    deletions: number[];
  };
}

export interface FixStoryManifest {
  id: string;
  runId: string;
  repoName: string;
  issueNumber: number;
  issueTitle: string;
  totalDurationSeconds: number;
  scenes: FixStoryScene[];
  metadata: {
    generatedAt: string;
    filesChanged: number;
    linesChanged: number;
    testsPassed: boolean;
    confidence: string;
    riskLevel: string;
  };
}

const WORDS_PER_SECOND = 2.3;

function estimateDuration(text: string): number {
  const words = text.split(/\s+/).length;
  return Math.max(5, Math.ceil(words / WORDS_PER_SECOND));
}

export function generateFixStoryManifest(run: AgentRun): FixStoryManifest {
  const issue = run.issue;
  const plan = run.plan;
  const artifacts = run.artifacts;
  const evaluation = run.evaluation;
  const changeIntent = artifacts.changeIntent;
  const testMatrix = artifacts.testMatrix;

  const scenes: FixStoryScene[] = [];

  // Scene 1: Intro
  const introNarration = `Let's look at how we fixed issue number ${issue?.number || "unknown"}: "${issue?.title || "a reported bug"}". This automated fix was generated by the BugBot agent, which analyzed the codebase, identified the root cause, and implemented a targeted patch.`;
  scenes.push({
    id: "intro",
    type: "intro",
    title: "The Bug Report",
    narration: introNarration,
    durationSeconds: estimateDuration(introNarration),
    visualConfig: {
      layout: "centered",
      background: "gradient",
      accentColor: "#8b5cf6",
      animation: "fade",
    },
    data: {
      issueNumber: issue?.number,
      issueTitle: issue?.title,
      repoName: run.repoName,
      labels: issue?.labels || [],
    },
  });

  // Scene 2: Bug Context
  const bugBody = issue?.body || "No description provided";
  const contextNarration = `The issue reported: ${truncate(bugBody, 300)}. ${
    issue?.comments?.length
      ? `There were ${issue.comments.length} comments providing additional context.`
      : ""
  }`;
  scenes.push({
    id: "bug-context",
    type: "bug_context",
    title: "Understanding the Bug",
    narration: contextNarration,
    durationSeconds: estimateDuration(contextNarration),
    visualConfig: {
      layout: "split",
      background: "dark",
      accentColor: "#ef4444",
      animation: "slide",
    },
    data: {
      issueBody: truncate(bugBody, 500),
      commentsCount: issue?.comments?.length || 0,
      labels: issue?.labels || [],
    },
  });

  // Scene 3: Root Cause Analysis
  const hypothesis = changeIntent?.hypothesis || plan?.strategy || "Identified through automated code analysis";
  const rootCauseNarration = `After analyzing the codebase, the agent determined the root cause: ${hypothesis}. ${
    plan?.tasks?.length
      ? `The fix strategy involved ${plan.tasks.length} steps: ${plan.tasks.map(t => t.title).join(", ")}.`
      : ""
  }`;
  scenes.push({
    id: "root-cause",
    type: "root_cause",
    title: "Root Cause Analysis",
    narration: rootCauseNarration,
    durationSeconds: estimateDuration(rootCauseNarration),
    visualConfig: {
      layout: "graph",
      background: "mesh",
      accentColor: "#a855f7",
      animation: "zoom",
    },
    data: {
      hypothesis,
      tasks: plan?.tasks || [],
      focusFiles: artifacts.changedFiles.map(f => f.path),
    },
  });

  // Scene 4: Diff Walkthrough
  const changedFiles = artifacts.changedFiles || [];
  const totalAdditions = changedFiles.reduce((sum, f) => sum + f.additions, 0);
  const totalDeletions = changedFiles.reduce((sum, f) => sum + f.deletions, 0);
  const diffNarration = `The patch modifies ${changedFiles.length} file${changedFiles.length !== 1 ? "s" : ""}, adding ${totalAdditions} lines and removing ${totalDeletions} lines. ${
    changedFiles.slice(0, 3).map(f => `${f.path} was updated with ${f.additions} additions and ${f.deletions} deletions`).join(". ")
  }.${
    changedFiles.some(f => f.sensitive) ? " Note: some sensitive files were modified and require careful review." : ""
  }`;
  scenes.push({
    id: "diff-walkthrough",
    type: "diff_walkthrough",
    title: "The Fix",
    narration: diffNarration,
    durationSeconds: estimateDuration(diffNarration) + 5,
    visualConfig: {
      layout: "code",
      background: "dark",
      accentColor: "#22d3ee",
      animation: "typewriter",
      codeHighlight: {
        language: detectLanguage(changedFiles[0]?.path || ""),
        theme: "dark",
        additions: [1, 2, 3],
        deletions: [],
      },
    },
    data: {
      changedFiles,
      diffStat: artifacts.diffStat,
      patch: truncate(artifacts.patch, 2000),
      totalAdditions,
      totalDeletions,
    },
  });

  // Scene 5: Test Results
  const testsPassed = artifacts.validation.overallStatus === "passed";
  const commands = artifacts.validation.commands || [];
  const passedCmds = commands.filter(c => c.exitCode === 0);
  const testNarration = testsPassed
    ? `All ${commands.length} validation commands passed successfully. ${
        passedCmds.map(c => `"${c.command}" completed in ${c.durationMs}ms`).join(". ")
      }. The fix is verified.`
    : `${passedCmds.length} of ${commands.length} validation commands passed. ${
        commands.filter(c => c.exitCode !== 0).map(c => `"${c.command}" had issues`).join(". ")
      }. Manual review is recommended.`;
  scenes.push({
    id: "test-results",
    type: "test_results",
    title: "Validation Results",
    narration: testNarration,
    durationSeconds: estimateDuration(testNarration),
    visualConfig: {
      layout: "terminal",
      background: "dark",
      accentColor: testsPassed ? "#22c55e" : "#f59e0b",
      animation: "typewriter",
    },
    data: {
      overallStatus: artifacts.validation.overallStatus,
      commands,
      testMatrix: testMatrix?.suites || [],
      qualityGates: artifacts.qualityGates?.gates || [],
      passRate: testMatrix?.passRate || 0,
    },
  });

  // Scene 6: Summary
  const summaryNarration = `In summary, this automated fix addresses issue number ${issue?.number || "unknown"} with a ${evaluation.confidenceLevel}-confidence, ${evaluation.riskLevel}-risk patch. ${
    evaluation.confidenceReasons?.slice(0, 2).join(". ") || ""
  }. The recommended action is: ${artifacts.qualityGates?.recommendation || "review"}.`;
  scenes.push({
    id: "summary",
    type: "summary",
    title: "Fix Summary",
    narration: summaryNarration,
    durationSeconds: estimateDuration(summaryNarration),
    visualConfig: {
      layout: "centered",
      background: "gradient",
      accentColor: "#8b5cf6",
      animation: "fade",
    },
    data: {
      evaluation,
      recommendation: artifacts.qualityGates?.recommendation,
      prUrl: run.approval?.prUrl,
      branchName: run.approval?.branchName,
    },
  });

  const totalDuration = scenes.reduce((sum, s) => sum + s.durationSeconds, 0);

  return {
    id: `fix-story-${run.id}`,
    runId: run.id,
    repoName: run.repoName,
    issueNumber: issue?.number || 0,
    issueTitle: issue?.title || "Unknown issue",
    totalDurationSeconds: totalDuration,
    scenes,
    metadata: {
      generatedAt: new Date().toISOString(),
      filesChanged: changedFiles.length,
      linesChanged: totalAdditions + totalDeletions,
      testsPassed,
      confidence: evaluation.confidenceLevel,
      riskLevel: evaluation.riskLevel,
    },
  };
}

export function formatFixStoryDuration(manifest: FixStoryManifest): string {
  const minutes = Math.floor(manifest.totalDurationSeconds / 60);
  const seconds = manifest.totalDurationSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

export function getFixStoryScenesForPhase(
  manifest: FixStoryManifest,
  phase: FixStoryScene["type"],
): FixStoryScene[] {
  return manifest.scenes.filter((s) => s.type === phase);
}

function truncate(text: string, limit: number): string {
  if (text.length <= limit) return text;
  return text.slice(0, limit - 3) + "...";
}

function detectLanguage(filePath: string): string {
  const ext = filePath.split(".").pop()?.toLowerCase() || "";
  const langMap: Record<string, string> = {
    ts: "typescript",
    tsx: "typescript",
    js: "javascript",
    jsx: "javascript",
    py: "python",
    go: "go",
    rs: "rust",
    rb: "ruby",
    java: "java",
    css: "css",
    scss: "scss",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
  };
  return langMap[ext] || "text";
}
