import type { ConnectorManifest } from "../types/capability";

export const VECTOR_STORE_MANIFESTS: ConnectorManifest[] = [
  {
    id: "supabase-pgvector",
    capability: "vector-store",
    nameKey: "CONNECTOR$PGVECTOR_NAME",
    descriptionKey: "CONNECTOR$PGVECTOR_DESC",
    // Authentication is the app's existing Supabase session; there is nothing
    // extra to supply, which is why this is the zero-configuration default.
    authKind: "none",
    fields: [],
    probe: {
      vantage: ["browser", "edge"],
      request: {
        method: "POST",
        pathTemplate: "/rest/v1/rpc/environment_installed_extensions",
      },
      checks: [
        {
          id: "extension",
          labelKey: "PROBE$CHECK_PGVECTOR",
          kind: "status-in",
          statuses: [200],
        },
      ],
    },
    egress: [],
    docsUrl: "https://supabase.com/docs/guides/ai/vector-columns",
    logo: "pgvector.svg",
    residency: ["us", "eu", "in", "global"],
    maturity: "ga",
  },
  {
    id: "pinecone",
    capability: "vector-store",
    nameKey: "CONNECTOR$PINECONE_NAME",
    descriptionKey: "CONNECTOR$PINECONE_DESC",
    authKind: "api-key",
    hostOverride: {
      field: "indexHost",
      baseUrlTemplate: "https://{{indexHost}}",
    },
    fields: [
      {
        name: "apiKey",
        kind: "password",
        secret: true,
        required: true,
        labelKey: "CONNECTOR$FIELD_API_KEY",
        redact: "last4",
      },
      {
        name: "indexHost",
        kind: "host",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_PINECONE_INDEX_HOST",
        helpKey: "CONNECTOR$FIELD_PINECONE_INDEX_HOST_HELP",
        placeholderKey: "CONNECTOR$FIELD_PINECONE_INDEX_HOST_PLACEHOLDER",
      },
      {
        name: "namespace",
        kind: "text",
        secret: false,
        required: false,
        labelKey: "CONNECTOR$FIELD_NAMESPACE",
        helpKey: "CONNECTOR$FIELD_NAMESPACE_HELP",
      },
    ],
    operations: [
      { id: "query", method: "POST", pathTemplate: "/query", params: [] },
      {
        id: "upsert",
        method: "POST",
        pathTemplate: "/vectors/upsert",
        params: [],
      },
      {
        id: "delete",
        method: "POST",
        pathTemplate: "/vectors/delete",
        params: [],
      },
      {
        id: "describe",
        method: "GET",
        pathTemplate: "/describe_index_stats",
        params: [],
      },
    ],
    probe: {
      vantage: ["edge", "runtime"],
      request: { method: "GET", pathTemplate: "/describe_index_stats" },
      checks: [
        {
          id: "auth",
          labelKey: "PROBE$CHECK_AUTH",
          kind: "status-in",
          statuses: [200],
        },
        {
          id: "dimension",
          labelKey: "PROBE$CHECK_INDEX_DIMENSION",
          kind: "json-pointer-present",
          pointer: "/dimension",
        },
      ],
    },
    egress: [
      {
        host: "*.pinecone.io",
        port: 443,
        purposeKey: "PROBE$EGRESS_PINECONE",
        mirrorable: false,
      },
    ],
    docsUrl: "https://docs.pinecone.io/reference/api",
    logo: "pinecone.svg",
    residency: ["us", "eu", "global"],
    maturity: "beta",
  },
  {
    id: "qdrant",
    capability: "vector-store",
    nameKey: "CONNECTOR$QDRANT_NAME",
    descriptionKey: "CONNECTOR$QDRANT_DESC",
    authKind: "api-key",
    hostOverride: {
      field: "instanceHost",
      baseUrlTemplate: "https://{{instanceHost}}",
    },
    fields: [
      {
        name: "instanceHost",
        kind: "host",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_INSTANCE_HOST",
      },
      {
        name: "apiKey",
        kind: "password",
        secret: true,
        required: false,
        labelKey: "CONNECTOR$FIELD_API_KEY",
        helpKey: "CONNECTOR$FIELD_QDRANT_KEY_HELP",
        redact: "last4",
      },
      {
        name: "collection",
        kind: "text",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_COLLECTION",
      },
    ],
    operations: [
      {
        id: "query",
        method: "POST",
        pathTemplate: "/collections/{{collection}}/points/search",
        params: ["collection"],
      },
      {
        id: "upsert",
        method: "PUT",
        pathTemplate: "/collections/{{collection}}/points",
        params: ["collection"],
      },
      {
        id: "delete",
        method: "POST",
        pathTemplate: "/collections/{{collection}}/points/delete",
        params: ["collection"],
      },
    ],
    probe: {
      vantage: ["runtime", "edge"],
      request: { method: "GET", pathTemplate: "/collections/{{collection}}" },
      checks: [
        {
          id: "auth",
          labelKey: "PROBE$CHECK_AUTH",
          kind: "status-in",
          statuses: [200],
        },
        {
          id: "collection",
          labelKey: "PROBE$CHECK_COLLECTION",
          kind: "json-pointer-present",
          pointer: "/result/status",
        },
      ],
    },
    egress: [],
    docsUrl: "https://qdrant.tech/documentation/concepts/points/",
    logo: "qdrant.svg",
    residency: ["us", "eu", "in", "global"],
    maturity: "beta",
  },
  {
    id: "weaviate",
    capability: "vector-store",
    nameKey: "CONNECTOR$WEAVIATE_NAME",
    descriptionKey: "CONNECTOR$WEAVIATE_DESC",
    authKind: "api-key",
    hostOverride: {
      field: "instanceHost",
      baseUrlTemplate: "https://{{instanceHost}}/v1",
    },
    fields: [
      {
        name: "instanceHost",
        kind: "host",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_INSTANCE_HOST",
      },
      {
        name: "apiKey",
        kind: "password",
        secret: true,
        required: false,
        labelKey: "CONNECTOR$FIELD_API_KEY",
        redact: "last4",
      },
      {
        name: "className",
        kind: "text",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_WEAVIATE_CLASS",
      },
    ],
    operations: [
      { id: "query", method: "POST", pathTemplate: "/graphql", params: [] },
      { id: "upsert", method: "POST", pathTemplate: "/objects", params: [] },
      {
        id: "delete",
        method: "DELETE",
        pathTemplate: "/objects/{{className}}/{{objectId}}",
        params: ["className", "objectId"],
      },
    ],
    probe: {
      vantage: ["runtime", "edge"],
      request: { method: "GET", pathTemplate: "/meta" },
      checks: [
        {
          id: "auth",
          labelKey: "PROBE$CHECK_AUTH",
          kind: "status-in",
          statuses: [200],
        },
        {
          id: "version",
          labelKey: "PROBE$CHECK_VERSION",
          kind: "json-pointer-present",
          pointer: "/version",
        },
      ],
      versionSource: { from: "json", pointer: "/version" },
    },
    egress: [],
    docsUrl: "https://weaviate.io/developers/weaviate/api/rest",
    logo: "weaviate.svg",
    residency: ["us", "eu", "in", "global"],
    maturity: "beta",
  },
  {
    id: "elasticsearch",
    capability: "vector-store",
    nameKey: "CONNECTOR$ELASTICSEARCH_NAME",
    descriptionKey: "CONNECTOR$ELASTICSEARCH_DESC",
    authKind: "api-key",
    hostOverride: {
      field: "instanceHost",
      baseUrlTemplate: "https://{{instanceHost}}",
    },
    fields: [
      {
        name: "instanceHost",
        kind: "host",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_INSTANCE_HOST",
      },
      {
        name: "apiKey",
        kind: "password",
        secret: true,
        required: true,
        labelKey: "CONNECTOR$FIELD_API_KEY",
        helpKey: "CONNECTOR$FIELD_ES_KEY_HELP",
        redact: "last4",
      },
      {
        name: "index",
        kind: "text",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_INDEX",
      },
    ],
    operations: [
      {
        id: "query",
        method: "POST",
        pathTemplate: "/{{index}}/_search",
        params: ["index"],
      },
      {
        id: "upsert",
        method: "POST",
        pathTemplate: "/{{index}}/_doc/{{docId}}",
        params: ["index", "docId"],
      },
      {
        id: "delete",
        method: "DELETE",
        pathTemplate: "/{{index}}/_doc/{{docId}}",
        params: ["index", "docId"],
      },
    ],
    probe: {
      vantage: ["runtime", "edge"],
      request: { method: "GET", pathTemplate: "/{{index}}" },
      checks: [
        {
          id: "index",
          labelKey: "PROBE$CHECK_INDEX",
          kind: "status-in",
          statuses: [200],
        },
      ],
    },
    egress: [],
    docsUrl:
      "https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html",
    logo: "elasticsearch.svg",
    residency: ["us", "eu", "in", "global"],
    maturity: "experimental",
  },
  {
    id: "tigergraph",
    capability: "vector-store",
    nameKey: "CONNECTOR$TIGERGRAPH_NAME",
    descriptionKey: "CONNECTOR$TIGERGRAPH_DESC",
    authKind: "bearer-token",
    hostOverride: {
      field: "instanceHost",
      baseUrlTemplate: "https://{{instanceHost}}:9000",
    },
    fields: [
      {
        name: "instanceHost",
        kind: "host",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_INSTANCE_HOST",
      },
      {
        name: "graphName",
        kind: "text",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_GRAPH_NAME",
      },
      {
        name: "accessToken",
        kind: "password",
        secret: true,
        required: true,
        labelKey: "CONNECTOR$FIELD_ACCESS_TOKEN",
        helpKey: "CONNECTOR$FIELD_TIGERGRAPH_TOKEN_HELP",
        redact: "last4",
      },
      {
        name: "similarityQuery",
        kind: "text",
        secret: false,
        required: true,
        labelKey: "CONNECTOR$FIELD_TIGERGRAPH_QUERY",
        helpKey: "CONNECTOR$FIELD_TIGERGRAPH_QUERY_HELP",
        defaultValue: "vectorSearch",
      },
    ],
    operations: [
      {
        id: "query",
        method: "POST",
        pathTemplate: "/query/{{graphName}}/{{similarityQuery}}",
        params: ["graphName", "similarityQuery"],
      },
      {
        id: "upsert",
        method: "POST",
        pathTemplate: "/graph/{{graphName}}",
        params: ["graphName"],
      },
    ],
    probe: {
      vantage: ["runtime"],
      request: { method: "GET", pathTemplate: "/echo" },
      checks: [
        {
          id: "auth",
          labelKey: "PROBE$CHECK_AUTH",
          kind: "status-in",
          statuses: [200],
        },
      ],
    },
    egress: [],
    docsUrl:
      "https://docs.tigergraph.com/tigergraph-server/current/api/built-in-endpoints",
    logo: "tigergraph.svg",
    residency: ["us", "eu", "in", "global"],
    maturity: "experimental",
  },
];
