import rawRequirements from "../../../../config/environment-requirements.json";
import type { Capability, EgressHost } from "../types/capability";
import type {
  EnvScope,
  FeatureRequirement,
  RequirementNode,
} from "../types/requirements";

/**
 * The requirement graph is authored as JSON in `config/environment-requirements.json`
 * rather than TypeScript for one reason: `scripts/environment-preflight.mjs`
 * runs standalone on a customer's machine, with no build step and no bundler,
 * and it must check exactly the same list the UI shows. Two hand-maintained
 * copies would drift, and the copy that drifts is always the one nobody
 * looks at until an install fails.
 */

export interface EnvVarRequirement {
  name: string;
  scope: EnvScope;
  secret: boolean;
  expected?: string;
  autoGenerated?: boolean;
  purposeKey: string;
}

export interface EnvPairRequirement {
  id: string;
  a: { scope: EnvScope; name: string };
  b: { scope: EnvScope; name: string };
  purposeKey: string;
}

export interface HostBinaryRequirement {
  name: string;
  minVersion?: string;
  optional?: boolean;
  purposeKey: string;
}

export interface PgExtensionRequirement {
  name: string;
  optional?: boolean;
  purposeKey: string;
}

export interface StorageBucketRequirement {
  name: string;
  public: boolean;
  purposeKey: string;
}

export interface DeploymentDefect {
  id: string;
  nameKey: string;
  check: string;
  remediationKey: string;
}

interface RequirementsFile {
  schemaVersion: number;
  platformEgress: EgressHost[];
  featureEgress: EgressHost[];
  hostBinaries: HostBinaryRequirement[];
  pgExtensions: PgExtensionRequirement[];
  storageBuckets: StorageBucketRequirement[];
  envVars: EnvVarRequirement[];
  envPairs: EnvPairRequirement[];
  features: FeatureRequirement[];
  deploymentDefects: DeploymentDefect[];
}

const requirements = rawRequirements as unknown as RequirementsFile;

export const PLATFORM_EGRESS: EgressHost[] = requirements.platformEgress;
export const FEATURE_EGRESS: EgressHost[] = requirements.featureEgress;
export const HOST_BINARIES: HostBinaryRequirement[] = requirements.hostBinaries;
export const PG_EXTENSIONS: PgExtensionRequirement[] =
  requirements.pgExtensions;
export const STORAGE_BUCKETS: StorageBucketRequirement[] =
  requirements.storageBuckets;
export const ENV_VARS: EnvVarRequirement[] = requirements.envVars;
export const ENV_PAIRS: EnvPairRequirement[] = requirements.envPairs;
export const FEATURE_REQUIREMENTS: FeatureRequirement[] = requirements.features;
export const DEPLOYMENT_DEFECTS: DeploymentDefect[] =
  requirements.deploymentDefects;

export function getEnvPair(id: string): EnvPairRequirement | undefined {
  return ENV_PAIRS.find((pair) => pair.id === id);
}

export function getDeploymentDefect(id: string): DeploymentDefect | undefined {
  return DEPLOYMENT_DEFECTS.find((defect) => defect.id === id);
}

/** Stable identity for a requirement node -- React key, task key, probe key. */
export function requirementNodeId(node: RequirementNode): string {
  switch (node.kind) {
    case "capability":
      return `capability:${node.capability}`;
    case "env":
      return `env:${node.scope}:${node.name}`;
    case "env-pair":
      return `env-pair:${node.id}`;
    case "pg-extension":
      return `pg-extension:${node.name}`;
    case "host-binary":
      return `host-binary:${node.name}`;
    case "egress":
      return `egress:${node.host}:${node.port}`;
    case "inbound":
      return `inbound:${node.path}`;
    case "storage-bucket":
      return `storage-bucket:${node.name}`;
    case "deployment-defect":
      return `deployment-defect:${node.id}`;
    default: {
      // Exhaustiveness guard: a new node kind must extend this switch, or the
      // readiness report would silently collapse two requirements into one id.
      const never: never = node;
      return String(never);
    }
  }
}

/** Every capability referenced by at least one feature requirement. */
export function requiredCapabilities(): Capability[] {
  const seen = new Set<Capability>();
  for (const feature of FEATURE_REQUIREMENTS) {
    for (const entry of feature.requires) {
      if (entry.node.kind === "capability") seen.add(entry.node.capability);
    }
  }
  return [...seen];
}
