/**
 * Deterministic, code-first KT (knowledge-transfer) video manifest builder.
 *
 * Every sentence and every on-screen highlight is derived from real file
 * content passed in — real symbols, real line numbers, real imports. Nothing
 * is invented or sent through an LLM. This mirrors the product rule from the
 * original reel-studio pipeline: the video must show the real codebase and
 * point at it accurately, or say nothing at all.
 */

const WORDS_PER_SECOND = 2.3;
const MIN_SCENE_SECONDS = 6;
const FPS = 30;

const IGNORE_PATH =
  /(^|\/)(node_modules|dist|build|\.git|coverage|vendor|__pycache__|\.next|\.turbo)(\/|$)/i;
const NOISE_FILE =
  /(\.min\.|\.lock$|\.map$|package-lock\.json$|yarn\.lock$|pnpm-lock\.yaml$|\.snap$|\.d\.ts$)/i;
const TEST_FILE = /(\.|\/)(test|spec)\.|(^|\/)(tests?|__tests__)(\/|$)/i;

const SOURCE_EXT = new Set([
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "go",
  "rs",
  "java",
  "rb",
  "php",
  "cs",
  "kt",
  "swift",
  "scala",
  "c",
  "cc",
  "cpp",
  "h",
  "hpp",
  "vue",
  "svelte",
]);

const ENTRY_HINTS = [
  "src/main",
  "src/index",
  "src/app",
  "main.",
  "index.",
  "app.",
  "server.",
  "cli.",
  "__main__",
  "manage.py",
];

const extOf = (path: string): string =>
  path.split(".").pop()?.toLowerCase() || "";
const baseName = (path: string): string => path.split("/").pop() || path;
const nameNoExt = (path: string): string =>
  baseName(path).replace(/\.[a-z]+$/i, "");
const normalize = (p: string): string =>
  p.replace(/^\.\/+/, "").replace(/^\/+/, "");
const isSourceFile = (path: string): boolean =>
  SOURCE_EXT.has(extOf(path)) || /readme/i.test(baseName(path));

interface FileSymbol {
  name: string;
  line: number;
  kind:
    | "function"
    | "class"
    | "component"
    | "interface"
    | "type"
    | "const"
    | "default";
  exported: boolean;
}

export interface KtSourceRef {
  file_path: string;
  start_line: number;
  end_line: number;
  symbol_name?: string;
}

export interface KtSentence {
  sentence: string;
  source_refs: KtSourceRef[];
  on_screen_focus: string[];
}

export type KtSceneType =
  | "intro"
  | "concept"
  | "architecture"
  | "code"
  | "flow"
  | "diagram"
  | "repo-tree"
  | "recap";

export interface KtScene {
  id: number;
  /** Which sub-component renders this scene. Defaults are set by the
   * builders below; existing conversation-scoped call sites that only ever
   * produced "intro"/"code"/"recap" scenes are unaffected. */
  type: KtSceneType;
  file_path: string | null;
  title: string;
  code: string;
  highlight_lines: [number, number];
  narration_text: string;
  sentences: KtSentence[];
  focus_symbols: string[];
  durationInFrames: number;
  startFrame: number;
  endFrame: number;
  /** Raw Mermaid source for "architecture"/"flow"/"diagram" scenes — the
   * real diagram DeepWiki generated, pre-rendered to SVG once at manifest
   * build time (see kt-video-composition.tsx), never regenerated by an LLM. */
  mermaid?: string;
  /** File paths for "repo-tree" scenes. */
  tree_files?: string[];
}

export interface KtManifest {
  repo_name: string;
  scenes: KtScene[];
  totalFrames: number;
  fps: number;
  repo_files: string[];
}

/** Approximate import in-degree across the provided file set (no repo graph needed). */
function computeInDegree(
  fileContents: Record<string, string>,
): Map<string, number> {
  const paths = Object.keys(fileContents).map(normalize);
  const byNormalized = new Set(paths);
  const inDegree = new Map<string, number>();

  const resolveRelative = (fromPath: string, spec: string): string | null => {
    const fromDir = fromPath.split("/").slice(0, -1).join("/");
    const parts = (fromDir ? `${fromDir}/${spec}` : spec).split("/");
    const stack: string[] = [];
    for (const part of parts) {
      if (part === "." || part === "") continue;
      if (part === "..") stack.pop();
      else stack.push(part);
    }
    const guess = stack.join("/");
    const candidates = [
      guess,
      `${guess}.ts`,
      `${guess}.tsx`,
      `${guess}.js`,
      `${guess}.jsx`,
      `${guess}/index.ts`,
      `${guess}/index.tsx`,
      `${guess}/index.js`,
      `${guess}.py`,
      `${guess}.go`,
    ];
    return candidates.find((c) => byNormalized.has(c)) || null;
  };

  for (const [rawPath, content] of Object.entries(fileContents)) {
    const fromPath = normalize(rawPath);
    const importRe =
      /(?:import\s.+?from\s+|require\(|from\s+)['"]([^'"]+)['"]/g;
    let m: RegExpExecArray | null;
    while ((m = importRe.exec(content)) !== null) {
      const spec = m[1];
      if (!spec.startsWith(".")) continue;
      const target = resolveRelative(fromPath, spec);
      if (target) inDegree.set(target, (inDegree.get(target) || 0) + 1);
    }
  }
  return inDegree;
}

function rankFiles(
  fileContents: Record<string, string>,
  limit: number,
): string[] {
  const inDegree = computeInDegree(fileContents);

  const candidates = Object.keys(fileContents).filter((p) => {
    const n = normalize(p);
    if (IGNORE_PATH.test(n) || NOISE_FILE.test(n)) return false;
    if (!isSourceFile(n)) return false;
    const content = fileContents[p] || "";
    return content.trim().length >= 40;
  });

  const score = (path: string): number => {
    const n = normalize(path);
    const lower = n.toLowerCase();
    let s = 0;
    s += (inDegree.get(n) || 0) * 2;
    if (ENTRY_HINTS.some((h) => lower.includes(h))) s += 5;
    if (lower.startsWith("src/")) s += 2;
    const lines = (fileContents[path].match(/\n/g)?.length || 0) + 1;
    s += Math.min(lines / 40, 4);
    if (TEST_FILE.test(n)) s -= 6;
    if (/readme/i.test(baseName(n))) s += 3;
    if (/\.(json|ya?ml|css|scss|md)$/i.test(n) && !/readme/i.test(baseName(n)))
      s -= 3;
    return s;
  };

  return candidates
    .map((p) => ({ p, s: score(p) }))
    .sort((a, b) => b.s - a.s)
    .slice(0, limit)
    .map((x) => x.p);
}

function extractSymbols(path: string, content: string): FileSymbol[] {
  const lines = content.split("\n");
  const ext = extOf(path);
  const symbols: FileSymbol[] = [];
  const push = (s: FileSymbol) => {
    if (s.name && s.name.length >= 2) symbols.push(s);
  };

  for (let i = 0; i < lines.length; i += 1) {
    const trimmed = lines[i].trim();
    const ln = i + 1;
    let m: RegExpMatchArray | null;

    if (
      ["ts", "tsx", "js", "jsx", "mjs", "cjs", "vue", "svelte"].includes(ext)
    ) {
      if (
        (m = trimmed.match(
          /^export\s+default\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/,
        ))
      ) {
        push({ name: m[1], line: ln, kind: "default", exported: true });
      } else if (
        (m = trimmed.match(/^export\s+default\s+class\s+([A-Za-z0-9_]+)/))
      ) {
        push({ name: m[1], line: ln, kind: "default", exported: true });
      } else if (
        (m = trimmed.match(/^export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/))
      ) {
        push({ name: m[1], line: ln, kind: "function", exported: true });
      } else if ((m = trimmed.match(/^export\s+class\s+([A-Za-z0-9_]+)/))) {
        push({ name: m[1], line: ln, kind: "class", exported: true });
      } else if ((m = trimmed.match(/^export\s+interface\s+([A-Za-z0-9_]+)/))) {
        push({ name: m[1], line: ln, kind: "interface", exported: true });
      } else if ((m = trimmed.match(/^export\s+type\s+([A-Za-z0-9_]+)/))) {
        push({ name: m[1], line: ln, kind: "type", exported: true });
      } else if (
        (m = trimmed.match(/^export\s+const\s+([A-Za-z0-9_]+)\s*[=:]/))
      ) {
        push({
          name: m[1],
          line: ln,
          kind: /^[A-Z]/.test(m[1]) ? "component" : "const",
          exported: true,
        });
      } else if (
        (m = trimmed.match(/^(?:async\s+)?function\s+([A-Za-z0-9_]+)/))
      ) {
        push({ name: m[1], line: ln, kind: "function", exported: false });
      } else if ((m = trimmed.match(/^class\s+([A-Za-z0-9_]+)/))) {
        push({ name: m[1], line: ln, kind: "class", exported: false });
      }
    } else if (ext === "py") {
      if ((m = trimmed.match(/^(?:async\s+)?def\s+([A-Za-z0-9_]+)/))) {
        push({
          name: m[1],
          line: ln,
          kind: "function",
          exported: !trimmed.startsWith("_"),
        });
      } else if ((m = trimmed.match(/^class\s+([A-Za-z0-9_]+)/))) {
        push({ name: m[1], line: ln, kind: "class", exported: true });
      }
    } else if (ext === "go") {
      if ((m = trimmed.match(/^func\s+(?:\([^)]*\)\s*)?([A-Za-z0-9_]+)/))) {
        push({
          name: m[1],
          line: ln,
          kind: "function",
          exported: /^[A-Z]/.test(m[1]),
        });
      }
    } else if (
      [
        "rs",
        "java",
        "cs",
        "kt",
        "swift",
        "scala",
        "rb",
        "php",
        "c",
        "cc",
        "cpp",
      ].includes(ext)
    ) {
      if (
        (m = trimmed.match(
          /(?:pub\s+|public\s+|private\s+)?(?:async\s+)?(?:fn|func|def|function)\s+([A-Za-z0-9_]+)/,
        ))
      ) {
        push({ name: m[1], line: ln, kind: "function", exported: true });
      } else if (
        (m = trimmed.match(
          /(?:pub\s+|public\s+)?(?:class|struct|interface|trait|enum)\s+([A-Za-z0-9_]+)/,
        ))
      ) {
        push({ name: m[1], line: ln, kind: "class", exported: true });
      }
    }
  }
  return symbols;
}

function extractImports(content: string, max = 5): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const re =
    /(?:import\s.+?from\s+|require\(\s*|from\s+|use\s+)['"]([^'"]+)['"]/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null && out.length < max) {
    const spec = m[1];
    const label = spec.startsWith(".")
      ? baseName(spec).replace(/\.[a-z]+$/i, "")
      : spec.replace(/^@[^/]+\//, "").split("/")[0];
    if (label && !seen.has(label)) {
      seen.add(label);
      out.push(label);
    }
  }
  return out;
}

function roleForPath(path: string): string {
  const l = normalize(path).toLowerCase();
  if (/readme/i.test(baseName(l)))
    return "the project's front door — its README";
  if (/(^|\/)(pages|views|screens|routes)(\/|$)|page\.|route\./.test(l))
    return "a page that users actually land on";
  if (/context/.test(l)) return "state shared across the app via context";
  if (/(^|\/)hooks?(\/|$)|\buse[A-Z]/.test(baseName(path)))
    return "a reusable hook";
  if (/component/.test(l) || extOf(l) === "tsx" || extOf(l) === "jsx")
    return "a UI component";
  if (/(store|reducer|slice|redux|zustand)/.test(l))
    return "the state-management layer";
  if (/(route|controller|endpoint|api|handler|server)/.test(l))
    return "a backend entry point handling requests";
  if (/(service|client|provider)/.test(l))
    return "a service module that talks to the outside world";
  if (/(model|schema|entity|types?)/.test(l))
    return "where the core data shapes are defined";
  if (/(util|helper|lib|common)/.test(l))
    return "a shared utility module the rest of the code leans on";
  if (/(config|setup|env)/.test(l))
    return "configuration that wires the project together";
  if (/main\.|index\.|app\.|__main__|cli\./.test(l))
    return "an entry point where execution begins";
  return "a core module in this codebase";
}

const kindWord = (k: FileSymbol["kind"]): string => {
  switch (k) {
    case "component":
      return "component";
    case "class":
      return "class";
    case "interface":
      return "interface";
    case "type":
      return "type";
    case "default":
      return "main export";
    case "const":
      return "value";
    default:
      return "function";
  }
};

const joinHuman = (items: string[]): string => {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(", ")}, and ${items[items.length - 1]}`;
};

function pickPrimary(symbols: FileSymbol[]): FileSymbol | null {
  if (symbols.length === 0) return null;
  const def = symbols.find((s) => s.kind === "default");
  if (def) return def;
  const exported = symbols.filter((s) => s.exported);
  const pool = exported.length ? exported : symbols;
  const meaty = pool.find((s) =>
    ["function", "component", "class", "default"].includes(s.kind),
  );
  return meaty || pool[0];
}

function buildCodeScene(id: number, path: string, content: string): KtScene {
  const lines = content.split("\n");
  const lineCount = lines.length;
  const file = baseName(path);
  const title = nameNoExt(path);
  const role = roleForPath(path);
  const symbols = extractSymbols(path, content);
  const imports = extractImports(content);
  const primary = pickPrimary(symbols);

  const refTo = (start: number, end: number, symbol?: string): KtSourceRef => ({
    file_path: path,
    start_line: Math.max(1, start),
    end_line: Math.min(lineCount, Math.max(start, end)),
    symbol_name: symbol,
  });

  const sentences: KtSentence[] = [];
  const focus: string[] = [];

  sentences.push({
    sentence: `Let's open ${title}. This is ${role}.`,
    source_refs: [refTo(1, Math.min(lineCount, 12))],
    on_screen_focus: [file],
  });

  if (imports.length) {
    sentences.push({
      sentence: `Right at the top it pulls in ${joinHuman(imports)}, so it builds directly on ${imports.length > 1 ? "those pieces" : "that piece"} rather than reinventing them.`,
      source_refs: [refTo(1, Math.min(lineCount, 15))],
      on_screen_focus: imports.slice(0, 3),
    });
  }

  let highlight: [number, number] = [1, Math.min(lineCount, 16)];

  if (primary) {
    focus.push(primary.name);
    const next = symbols
      .filter((s) => s.line > primary.line)
      .sort((a, b) => a.line - b.line)[0];
    const blockEnd = next
      ? Math.min(next.line - 1, primary.line + 30)
      : Math.min(lineCount, primary.line + 24);
    highlight = [primary.line, Math.max(primary.line + 1, blockEnd)];

    sentences.push({
      sentence: `The heart of this file is ${primary.name}, the ${kindWord(primary.kind)} starting on line ${primary.line}. That's the part doing the real work here.`,
      source_refs: [refTo(primary.line, blockEnd, primary.name)],
      on_screen_focus: [primary.name],
    });

    const others = symbols.filter((s) => s.name !== primary.name && s.exported);
    if (others.length) {
      const secondary = others.slice(0, 3).map((s) => s.name);
      secondary.forEach((n) => focus.push(n));
      const second = others[0];
      sentences.push({
        sentence: `It also exposes ${joinHuman(secondary)}, which is how the rest of the codebase reaches into this module.`,
        source_refs: [
          refTo(second.line, Math.min(lineCount, second.line + 8), second.name),
        ],
        on_screen_focus: secondary,
      });
    } else {
      sentences.push({
        sentence: `Everything else in the file exists to support ${primary.name}, so once you understand it, you understand this file.`,
        source_refs: [refTo(highlight[0], highlight[1], primary.name)],
        on_screen_focus: [primary.name],
      });
    }
  } else {
    sentences.push({
      sentence: `This file is mostly ${/\.(json|ya?ml)$/i.test(path) ? "configuration data" : "declarative content"}, and these top lines are the part worth knowing.`,
      source_refs: [refTo(1, Math.min(lineCount, 20))],
      on_screen_focus: [file],
    });
  }

  const narration_text = sentences.map((s) => s.sentence).join(" ");
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: "code",
    file_path: path,
    title,
    code: content,
    highlight_lines: highlight,
    narration_text,
    sentences,
    focus_symbols: Array.from(new Set(focus)).slice(0, 6),
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
  };
}

function detectTech(fileContents: Record<string, string>): string[] {
  const exts = new Set(Object.keys(fileContents).map(extOf));
  const tech: string[] = [];
  if (exts.has("tsx") || exts.has("jsx")) tech.push("React");
  if (exts.has("ts") || exts.has("tsx")) tech.push("TypeScript");
  else if (exts.has("js") || exts.has("jsx") || exts.has("mjs"))
    tech.push("JavaScript");
  if (exts.has("py")) tech.push("Python");
  if (exts.has("go")) tech.push("Go");
  if (exts.has("rs")) tech.push("Rust");
  return Array.from(new Set(tech));
}

function buildIntroScene(
  id: number,
  repoName: string,
  fileContents: Record<string, string>,
  rankedFiles: string[],
): KtScene {
  const openerPath =
    rankedFiles.find((p) => /readme/i.test(baseName(p))) ||
    rankedFiles.find((p) =>
      ENTRY_HINTS.some((h) => normalize(p).toLowerCase().includes(h)),
    ) ||
    rankedFiles[0];
  const content = fileContents[openerPath] || "";
  const lineCount = content.split("\n").length || 1;
  const tech = detectTech(fileContents);
  const totalFiles = Object.keys(fileContents).length;

  const ref: KtSourceRef = {
    file_path: openerPath,
    start_line: 1,
    end_line: Math.min(lineCount, 20),
  };

  const sentences: KtSentence[] = [
    {
      sentence: `Welcome — let's walk through ${repoName} together.`,
      source_refs: [ref],
      on_screen_focus: [baseName(openerPath)],
    },
    {
      sentence: tech.length
        ? `It's built with ${joinHuman(tech)}, and this walkthrough covers ${totalFiles} file${totalFiles === 1 ? "" : "s"}.`
        : `This walkthrough covers ${totalFiles} file${totalFiles === 1 ? "" : "s"}, focusing on the ones that matter most.`,
      source_refs: [ref],
      on_screen_focus: [],
    },
  ];

  const narration_text = sentences.map((s) => s.sentence).join(" ");
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: "intro",
    file_path: openerPath,
    title: repoName,
    code: content,
    highlight_lines: [1, Math.min(lineCount, 12)],
    narration_text,
    sentences,
    focus_symbols: [],
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
  };
}

/**
 * Closing recap scene — grounded only in symbols/files the walkthrough
 * actually covered (pulled from the already-built code scenes), never
 * inventing anything new. Skipped when there's nothing real to recap.
 */
function buildSummaryScene(
  id: number,
  repoName: string,
  codeScenes: KtScene[],
): KtScene | null {
  if (!codeScenes.length) return null;

  const fileNames = codeScenes.map((s) => s.title);
  const allSymbols = Array.from(
    new Set(codeScenes.flatMap((s) => s.focus_symbols)),
  ).slice(0, 6);
  const last = codeScenes[codeScenes.length - 1];

  const sentences: KtSentence[] = [
    {
      sentence: `That covers ${repoName}'s core files: ${joinHuman(fileNames)}.`,
      source_refs: codeScenes.map((s) => ({
        file_path: s.file_path ?? s.title,
        start_line: s.highlight_lines[0],
        end_line: s.highlight_lines[1],
      })),
      on_screen_focus: fileNames,
    },
  ];

  if (allSymbols.length) {
    sentences.push({
      sentence: `The parts worth remembering are ${joinHuman(allSymbols)} — start there next time you're back in this code.`,
      source_refs: [
        {
          file_path: last.file_path ?? last.title,
          start_line: last.highlight_lines[0],
          end_line: last.highlight_lines[1],
        },
      ],
      on_screen_focus: allSymbols,
    });
  }

  const narration_text = sentences.map((s) => s.sentence).join(" ");
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: "recap",
    file_path: null,
    title: "Recap",
    code: fileNames.map((f) => `✓ ${f}`).join("\n"),
    highlight_lines: [1, fileNames.length],
    narration_text,
    sentences,
    focus_symbols: allSymbols,
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
  };
}

/**
 * Builds a deterministic KT-video manifest from real file contents.
 * `fileContents` maps a repo-relative path to its full text content.
 */
export function buildKtManifest(
  repoName: string,
  fileContents: Record<string, string>,
  maxScenes = 8,
  includeSummary = true,
): KtManifest {
  const entries = Object.entries(fileContents).filter(
    ([, c]) => c.trim().length > 0,
  );
  const asRecord = Object.fromEntries(entries);
  const ranked = rankFiles(asRecord, Math.max(1, maxScenes - 1));

  const scenes: KtScene[] = [];
  let id = 0;

  if (ranked.length) {
    scenes.push(buildIntroScene(id, repoName, asRecord, ranked));
    id += 1;
  }

  const codeScenes: KtScene[] = [];
  for (const path of ranked) {
    const scene = buildCodeScene(id, path, asRecord[path]);
    scenes.push(scene);
    codeScenes.push(scene);
    id += 1;
  }

  if (includeSummary) {
    const summary = buildSummaryScene(id, repoName, codeScenes);
    if (summary) {
      scenes.push(summary);
      id += 1;
    }
  }

  let cursor = 0;
  for (const scene of scenes) {
    scene.startFrame = cursor;
    cursor += scene.durationInFrames;
    scene.endFrame = cursor;
  }

  return {
    repo_name: repoName,
    scenes,
    totalFrames: Math.max(1, cursor),
    fps: FPS,
    repo_files: Object.keys(fileContents),
  };
}

// ---------------------------------------------------------------------------
// KnowledgePage-driven manifest — builds on a DeepWiki-normalized page
// instead of hand-picked conversation files. Still fully deterministic: no
// LLM call in this path. See src/lib/knowledge/knowledge-engine.ts for the
// KnowledgePage/RepositorySnapshot/KnowledgeDiagram shapes.
// ---------------------------------------------------------------------------

interface KtKnowledgeDiagram {
  id: string;
  type: "architecture" | "dependency" | "flow" | "sequence" | "other";
  mermaid: string;
}

interface KtKnowledgePage {
  id: string;
  title: string;
  description: string;
  relevantFiles: { path: string }[];
  diagrams: KtKnowledgeDiagram[];
}

function buildKnowledgeIntroScene(id: number, page: KtKnowledgePage): KtScene {
  const sentence: KtSentence = {
    sentence: page.description || `Let's walk through ${page.title}.`,
    source_refs: [],
    on_screen_focus: [],
  };
  const narration_text = sentence.sentence;
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: "intro",
    file_path: null,
    title: page.title,
    code: "",
    highlight_lines: [1, 1],
    narration_text,
    sentences: [sentence],
    focus_symbols: [],
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
  };
}

const DIAGRAM_SCENE_TYPE: Record<KtKnowledgeDiagram["type"], KtSceneType> = {
  architecture: "architecture",
  dependency: "architecture",
  flow: "flow",
  sequence: "flow",
  other: "diagram",
};

function buildDiagramScene(
  id: number,
  pageTitle: string,
  diagram: KtKnowledgeDiagram,
): KtScene {
  const sentence: KtSentence = {
    sentence: `Here's the real ${diagram.type} diagram for ${pageTitle}, generated from the actual codebase.`,
    source_refs: [],
    on_screen_focus: [],
  };
  const narration_text = sentence.sentence;
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: DIAGRAM_SCENE_TYPE[diagram.type],
    file_path: null,
    title: pageTitle,
    code: "",
    highlight_lines: [1, 1],
    narration_text,
    sentences: [sentence],
    focus_symbols: [],
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
    mermaid: diagram.mermaid,
  };
}

function buildRepoTreeScene(
  id: number,
  pageTitle: string,
  repoFiles: string[],
): KtScene | null {
  if (!repoFiles.length) return null;
  const shown = repoFiles.slice(0, 40);
  const sentence: KtSentence = {
    sentence: `Here's where ${pageTitle} lives in the repo — ${repoFiles.length} file${repoFiles.length === 1 ? "" : "s"} in scope.`,
    source_refs: [],
    on_screen_focus: shown.slice(0, 6),
  };
  const narration_text = sentence.sentence;
  const words = narration_text.trim().split(/\s+/).filter(Boolean).length;
  const duration_seconds = Math.max(
    MIN_SCENE_SECONDS,
    Math.ceil(words / WORDS_PER_SECOND) + 2,
  );

  return {
    id,
    type: "repo-tree",
    file_path: null,
    title: pageTitle,
    code: "",
    highlight_lines: [1, 1],
    narration_text,
    sentences: [sentence],
    focus_symbols: [],
    durationInFrames: Math.round(duration_seconds * FPS),
    startFrame: 0,
    endFrame: 0,
    tree_files: shown,
  };
}

/**
 * Builds a deterministic KT-video manifest from a DeepWiki-normalized
 * KnowledgePage instead of hand-picked conversation files. No LLM call —
 * reuses the same real-file/real-symbol extraction as buildKtManifest, just
 * scoped to the page's relevantFiles, and renders the page's real Mermaid
 * diagrams (never re-generating them) as their own scenes.
 *
 * `fileContents` must already contain the real text of every path in
 * `page.relevantFiles` (the caller resolves these from the same repository
 * snapshot DeepWiki analyzed — see kt-page.tsx). `repoFiles` is the full
 * file list shown in an optional repo-tree scene.
 */
export function buildKtManifestFromKnowledgePage(
  page: KtKnowledgePage,
  fileContents: Record<string, string>,
  repoFiles: string[] = [],
  maxCodeScenes = 5,
): KtManifest {
  const scenes: KtScene[] = [];
  let id = 0;

  scenes.push(buildKnowledgeIntroScene(id, page));
  id += 1;

  for (const diagram of page.diagrams) {
    scenes.push(buildDiagramScene(id, page.title, diagram));
    id += 1;
  }

  if (!page.diagrams.length) {
    const treeScene = buildRepoTreeScene(id, page.title, repoFiles);
    if (treeScene) {
      scenes.push(treeScene);
      id += 1;
    }
  }

  const codeScenes: KtScene[] = [];
  for (const { path } of page.relevantFiles.slice(0, maxCodeScenes)) {
    const content = fileContents[path];
    if (!content?.trim()) continue;
    const scene = buildCodeScene(id, path, content);
    scenes.push(scene);
    codeScenes.push(scene);
    id += 1;
  }

  const summary = buildSummaryScene(id, page.title, codeScenes);
  if (summary) {
    scenes.push(summary);
    id += 1;
  }

  let cursor = 0;
  for (const scene of scenes) {
    scene.startFrame = cursor;
    cursor += scene.durationInFrames;
    scene.endFrame = cursor;
  }

  return {
    repo_name: page.title,
    scenes,
    totalFrames: Math.max(1, cursor),
    fps: FPS,
    repo_files: repoFiles,
  };
}
