export const ONBOARDING_CONTROL_TOOL_NAME = "onboarding_control";

/**
 * Action discriminator generated by the SDK for a client-defined tool
 * (`ClientAction_<tool-name>`), matching the convention in
 * `src/constants/canvas-ui.ts`.
 */
export const ONBOARDING_CONTROL_ACTION_KIND =
  `ClientAction_${ONBOARDING_CONTROL_TOOL_NAME}` as const;

/**
 * Prefix on the message posted back to the agent after an asynchronous
 * onboarding command completes, mirroring
 * `CHILD_CONVERSATION_RESULT_PREFIX`. The payload that follows is always a
 * redacted receipt -- never a credential.
 */
export const ONBOARDING_RESULT_PREFIX = "[onboarding result] ";

/**
 * Commands the agent may issue.
 *
 * The complete set ships at once, deliberately. `src/api/agent-server-adapter.ts`
 * documents that the agent-server caches a client tool's schema per tool NAME
 * for the lifetime of its process and rejects re-registration with a different
 * schema -- so growing this enum release by release would break every
 * long-running dev and production agent-server on deploy. Commands that are
 * not implemented yet return a `not_implemented` receipt instead of being
 * absent from the schema.
 */
export const ONBOARDING_CONTROL_COMMANDS = [
  "show_provider_picker",
  "request_credentials",
  "run_probe",
  "show_checklist",
  "propose_profile_change",
  "navigate",
  "generate_handoff_packet",
  "assign_task",
] as const;

export type OnboardingControlCommand =
  (typeof ONBOARDING_CONTROL_COMMANDS)[number];

export const ONBOARDING_PROBE_KINDS = [
  "connection",
  "egress",
  "pg-extensions",
  "backend-key",
  "webhook-ingress",
  "clock-skew",
  "host-prereqs",
  "deployment-defects",
] as const;

export const ONBOARDING_VIEWS = [
  "overview",
  "connections",
  "network",
  "requirements",
  "runbook",
] as const;
