// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/conversations": {
    params: {};
  };
  "/conversations/:conversationId/panel": {
    params: {
      "conversationId": string;
    };
  };
  "/conversations/:conversationId": {
    params: {
      "conversationId": string;
    };
  };
  "/launch": {
    params: {};
  };
  "/customize": {
    params: {};
  };
  "/skills": {
    params: {};
  };
  "/plugins": {
    params: {};
  };
  "/mcp": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/llm": {
    params: {};
  };
  "/settings/agent": {
    params: {};
  };
  "/settings/agents": {
    params: {};
  };
  "/settings/condenser": {
    params: {};
  };
  "/settings/agent-context": {
    params: {};
  };
  "/settings/verification": {
    params: {};
  };
  "/settings/app": {
    params: {};
  };
  "/settings/secrets": {
    params: {};
  };
  "/oauth/device/verify": {
    params: {};
  };
  "/automations": {
    params: {};
  };
  "/automations/templates": {
    params: {};
  };
  "/automations/new/:automationId": {
    params: {
      "automationId": string;
    };
  };
  "/automations/:automationId": {
    params: {
      "automationId": string;
    };
  };
  "/shared/conversations/:conversationId": {
    params: {
      "conversationId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/conversations" | "/conversations/:conversationId/panel" | "/conversations/:conversationId" | "/launch" | "/customize" | "/skills" | "/plugins" | "/mcp" | "/settings" | "/settings/llm" | "/settings/agent" | "/settings/agents" | "/settings/condenser" | "/settings/agent-context" | "/settings/verification" | "/settings/app" | "/settings/secrets" | "/oauth/device/verify" | "/automations" | "/automations/templates" | "/automations/new/:automationId" | "/automations/:automationId" | "/shared/conversations/:conversationId";
  };
  "routes/welcome.tsx": {
    id: "routes/welcome";
    page: "/";
  };
  "routes/root-layout.tsx": {
    id: "routes/root-layout";
    page: "/conversations" | "/conversations/:conversationId/panel" | "/conversations/:conversationId" | "/launch" | "/customize" | "/skills" | "/plugins" | "/mcp" | "/settings" | "/settings/llm" | "/settings/agent" | "/settings/agents" | "/settings/condenser" | "/settings/agent-context" | "/settings/verification" | "/settings/app" | "/settings/secrets" | "/oauth/device/verify" | "/automations" | "/automations/templates" | "/automations/new/:automationId" | "/automations/:automationId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/conversations";
  };
  "routes/conversation-panel.tsx": {
    id: "routes/conversation-panel";
    page: "/conversations/:conversationId/panel";
  };
  "routes/conversation.tsx": {
    id: "routes/conversation";
    page: "/conversations/:conversationId";
  };
  "routes/launch.tsx": {
    id: "routes/launch";
    page: "/launch";
  };
  "routes/extensions-hub.tsx": {
    id: "routes/extensions-hub";
    page: "/customize";
  };
  "routes/skills-settings.tsx": {
    id: "routes/skills-settings";
    page: "/skills";
  };
  "routes/skills-plugins.tsx": {
    id: "routes/skills-plugins";
    page: "/plugins";
  };
  "routes/mcp.tsx": {
    id: "routes/mcp";
    page: "/mcp";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings" | "/settings/llm" | "/settings/agent" | "/settings/agents" | "/settings/condenser" | "/settings/agent-context" | "/settings/verification" | "/settings/app" | "/settings/secrets";
  };
  "routes/settings-index.tsx": {
    id: "routes/settings-index";
    page: "/settings";
  };
  "routes/llm-settings.tsx": {
    id: "routes/llm-settings";
    page: "/settings/llm";
  };
  "routes/agent-settings.tsx": {
    id: "routes/agent-settings";
    page: "/settings/agent";
  };
  "routes/agent-profiles-settings.tsx": {
    id: "routes/agent-profiles-settings";
    page: "/settings/agents";
  };
  "routes/condenser-settings.tsx": {
    id: "routes/condenser-settings";
    page: "/settings/condenser";
  };
  "routes/agent-context-settings.tsx": {
    id: "routes/agent-context-settings";
    page: "/settings/agent-context";
  };
  "routes/verification-settings.tsx": {
    id: "routes/verification-settings";
    page: "/settings/verification";
  };
  "routes/app-settings.tsx": {
    id: "routes/app-settings";
    page: "/settings/app";
  };
  "routes/secrets-settings.tsx": {
    id: "routes/secrets-settings";
    page: "/settings/secrets";
  };
  "routes/device-verify.tsx": {
    id: "routes/device-verify";
    page: "/oauth/device/verify";
  };
  "routes/automations-list.tsx": {
    id: "routes/automations-list";
    page: "/automations";
  };
  "routes/automation-templates.tsx": {
    id: "routes/automation-templates";
    page: "/automations/templates";
  };
  "routes/automation-setup-route.tsx": {
    id: "routes/automation-setup-route";
    page: "/automations/new/:automationId";
  };
  "routes/automation-detail.tsx": {
    id: "routes/automation-detail";
    page: "/automations/:automationId";
  };
  "routes/shared-conversation.tsx": {
    id: "routes/shared-conversation";
    page: "/shared/conversations/:conversationId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/welcome": typeof import("./src/routes/welcome.tsx");
  "routes/root-layout": typeof import("./src/routes/root-layout.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/conversation-panel": typeof import("./src/routes/conversation-panel.tsx");
  "routes/conversation": typeof import("./src/routes/conversation.tsx");
  "routes/launch": typeof import("./src/routes/launch.tsx");
  "routes/extensions-hub": typeof import("./src/routes/extensions-hub.tsx");
  "routes/skills-settings": typeof import("./src/routes/skills-settings.tsx");
  "routes/skills-plugins": typeof import("./src/routes/skills-plugins.tsx");
  "routes/mcp": typeof import("./src/routes/mcp.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
  "routes/settings-index": typeof import("./src/routes/settings-index.tsx");
  "routes/llm-settings": typeof import("./src/routes/llm-settings.tsx");
  "routes/agent-settings": typeof import("./src/routes/agent-settings.tsx");
  "routes/agent-profiles-settings": typeof import("./src/routes/agent-profiles-settings.tsx");
  "routes/condenser-settings": typeof import("./src/routes/condenser-settings.tsx");
  "routes/agent-context-settings": typeof import("./src/routes/agent-context-settings.tsx");
  "routes/verification-settings": typeof import("./src/routes/verification-settings.tsx");
  "routes/app-settings": typeof import("./src/routes/app-settings.tsx");
  "routes/secrets-settings": typeof import("./src/routes/secrets-settings.tsx");
  "routes/device-verify": typeof import("./src/routes/device-verify.tsx");
  "routes/automations-list": typeof import("./src/routes/automations-list.tsx");
  "routes/automation-templates": typeof import("./src/routes/automation-templates.tsx");
  "routes/automation-setup-route": typeof import("./src/routes/automation-setup-route.tsx");
  "routes/automation-detail": typeof import("./src/routes/automation-detail.tsx");
  "routes/shared-conversation": typeof import("./src/routes/shared-conversation.tsx");
};